### ISSUE TITLE
Blacklist_DX11_game was modified or the version is not supported

### ISSUE THREAD

**Issue by gsergeantGTHB** [unixoide/5th-echelon#13]
Tried this on Steam version, followed instructions, got .DLL from 5th echeolon and used mpdataserver then I got this error

"Blacklist_DX11_game was modified or the version is not supported"

It works without .DLL but only Private, not Quick Match or Find Match

Here's the .exe from Steam copy: 
https://www.dropbox.com/scl/fi/rk9ua6hd33xzxocgs5cgh/Blacklist_DX11_game.zip?rlkey=yzjt5npw9zl5rt02pgi5rprcv&dl=0

**Comment by JordanLeich** [comment]
> Tried this on Steam version, followed instructions, got .DLL from 5th echeolon and used mpdataserver then I got this error
> 
> "Blacklist_DX11_game was modified or the version is not supported"
> 
> It works without .DLL but only Private, not Quick Match or Find Match
> 
> Here's the .exe from Steam copy: https://www.dropbox.com/scl/fi/rk9ua6hd33xzxocgs5cgh/Blacklist_DX11_game.zip?rlkey=yzjt5npw9zl5rt02pgi5rprcv&dl=0

First, the DX11 version of the game isn't supported yet (with the 5th echelon patch) so just use the file called blacklist_game.exe. Also, the 5th echelon patch and the mpdataserver fix are technically 2 different fixes but for now, you can just use the mpdataserver fix since it works better for playing online. Make sure you edit that hosts file using notepad with admin rights then run the mpdataserver.exe file and then run the game. Also make sure you uninstall or disable radmin or hamachi or anything that interferes with your ethernet or wifi network adapter.
