### ISSUE TITLE
Able to acess online but can't join friend  lobby or search quick match

### ISSUE THREAD

**Issue by zikenzi7** [unixoide/5th-echelon#16]
I can't play with any friends in my ubi account. I don't know why 
I turned off Windows Firewall and i opened ports for Blacklist on my router, set a static ip on my network adapter.
I got no VPNs or VPNs adapter in my network adapters.I just tried everything and i got no help.
Still i can join some guys, like 2 of 20 friends.
Friends don't have a VPNs or VPNs adapter, they turned off Windows Firewall and some of them opened ports.

![image](https://github.com/unixoide/5th-echelon/assets/155828302/b0b7eb0b-ddd7-4c02-9b94-857b025ad442)
![image](https://github.com/unixoide/5th-echelon/assets/155828302/00d1deab-1f31-4a6e-a4e9-36272f3d6de0)
![image](https://github.com/unixoide/5th-echelon/assets/155828302/763b7446-5ffa-4de7-98e0-41ce6219f07a)

**Comment by unixoide** [comment]
Where you always able to connect to the same 2 friends, or did it change?

Besides recommending to open ports and uninstall software like VPNs and virtualization (Hyper-V, Virtualbox, VMWare), I can't do much without more information. For additional help, I'd need a network log (e.g. from Wireshark) so that I can see what the game is doing. Such recordings can contain credentials though, so better share it privately as described [here](https://github.com/unixoide/5th-echelon/issues/10#issuecomment-1857497325).

**Comment by unixoide** [comment]
Published the newest version, please give it a try
